apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applications.ui.name }}
  namespace: {{ default "control-plane" .Release.Namespace }}
spec:
  replicas: {{ .Values.applications.ui.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.applications.ui.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.applications.ui.name }}      
        date: "{{ now | unixEpoch }}"
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {{ .Values.applications.ui.name }}
        image: {{ .Values.applications.ui.imageName }}:{{ .Values.applications.ui.imageTag }}
        envFrom:
        - configMapRef:
            name: {{ .Values.applications.ui.name }}-config
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1724
        resources:
          limits:
            cpu: {{ .Values.applications.ui.resources.limits.cpu }}
            memory: {{ .Values.applications.ui.resources.limits.memory }}
          requests:
            cpu: {{ .Values.applications.ui.resources.requests.cpu }}
            memory: {{ .Values.applications.ui.resources.requests.memory }}
        ports:
          - containerPort: 8080
            name: http
        readinessProbe:
          httpGet:
            path: /controlplane/api/ui/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /controlplane/api/ui/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
---