apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applications.jaegertracing.name }}-ui-svc
  namespace: {{ default "control-plane" .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.applications.jaegertracing.uiPort }}
      protocol: TCP
      targetPort: {{ .Values.applications.jaegertracing.uiPort }}
      name: http-ui
      nodePort: {{ .Values.applications.jaegertracing.extPort }}
  selector:
    app: {{ .Values.applications.jaegertracing.name }}
  type: NodePort
---